name: Conditional Step Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'Executer'

jobs:
  greeting_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
        if: github.event.inputs.name != 'Executer'  # Умова для пропуску кроку
